fn main() {
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "prepare_desktop",
            "inspect_setup",
            "configure_setup",
            "replace_credentials",
            "start_service",
            "stop_service",
            "repair_service",
            "open_token_page",
            "read_overview",
            "list_watches",
            "add_watch",
            "update_watch",
            "pause_watch",
            "resume_watch",
            "remove_watch",
            "search_targets",
            "list_snapshots",
            "compare_snapshots",
            "list_changes",
            "inspect_service",
            "migrate_service",
            "uninstall_service",
            "inspect_home",
            "select_home",
            "inspect_binding",
        ]),
    ))
    .expect("application configuration is invalid");
}
