import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { DesktopClient, type Invoke } from './client'
import { createMonitoringState } from './monitoring'
import { envelope, overview, watch } from './fixtures'

describe('monitoring state', () => {
  let visible = true
  const target = new EventTarget()
  beforeEach(() => { vi.useFakeTimers(); visible = true })
  afterEach(() => { vi.useRealTimers() })
  const make = (invoke: Invoke) => createMonitoringState(new DesktopClient(invoke), { intervalMs: 5000, now: () => 42, visible: () => visible, target })

  it('polls every five seconds only while visible and never overlaps reads', async () => {
    let release!: (value: unknown) => void
    const invoke = vi.fn().mockResolvedValueOnce(envelope('overview', overview)).mockImplementationOnce(() => new Promise(resolve => { release = resolve })).mockResolvedValue(envelope('overview', overview))
    const ui = make(invoke)
    ui.start(); await vi.advanceTimersByTimeAsync(0)
    expect(ui.state.overview?.watches).toHaveLength(1); expect(ui.state.lastReadAt).toBe(42)
    await vi.advanceTimersByTimeAsync(5000); expect(invoke).toHaveBeenCalledTimes(2)
    await vi.advanceTimersByTimeAsync(5000); expect(invoke).toHaveBeenCalledTimes(2)
    release(envelope('overview', overview)); await vi.advanceTimersByTimeAsync(0)
    visible = false; target.dispatchEvent(new Event('visibilitychange'))
    await vi.advanceTimersByTimeAsync(15000); expect(invoke).toHaveBeenCalledTimes(2)
    visible = true; target.dispatchEvent(new Event('visibilitychange')); await vi.advanceTimersByTimeAsync(0)
    expect(invoke).toHaveBeenCalledTimes(3)
    ui.dispose(); await vi.advanceTimersByTimeAsync(20000); expect(invoke).toHaveBeenCalledTimes(3)
    expect(invoke.mock.calls.every(call => call[0] === 'read_overview')).toBe(true)
  })
  it('keeps data on a failed refresh, marks it stale and blocks mutations', async () => {
    const invoke = vi.fn().mockResolvedValueOnce(envelope('overview', overview)).mockRejectedValueOnce('transport')
    const ui = make(invoke)
    expect(await ui.refresh()).toBe(true)
    expect(await ui.refresh()).toBe(false)
    expect(ui.state.stale).toBe(true); expect(ui.state.readError?.code).toBe('transport'); expect(ui.state.overview?.watches).toHaveLength(1)
    expect(await ui.add('bob', 300)).toBe(false)
    expect(invoke).toHaveBeenCalledTimes(2)
  })
  it('re-reads after a conflict and never replays an unknown outcome', async () => {
    const invoke = vi.fn()
      .mockResolvedValueOnce(envelope('overview', overview))
      .mockResolvedValueOnce(envelope('error', { code: 'watch_conflict', message: 'RAW', retryable: false }))
      .mockResolvedValueOnce(envelope('overview', { ...overview, watches: [{ ...watch, status: 'paused' }] }))
      .mockRejectedValueOnce('outcome_unknown')
      .mockResolvedValueOnce(envelope('overview', overview))
    const ui = make(invoke)
    await ui.refresh()
    expect(await ui.pause(watch)).toBe(false)
    expect(ui.state.error?.code).toBe('watch_conflict'); expect(ui.state.overview?.watches[0].status).toBe('paused')
    expect(await ui.add('bob', 600)).toBe(false)
    expect(ui.state.outcomeUnknown).toBe(true)
    expect(invoke.mock.calls.map(call => call[0])).toEqual(['read_overview', 'pause_watch', 'read_overview', 'add_watch', 'read_overview'])
    expect(JSON.stringify(ui.state)).not.toContain('RAW')
  })
  it('reconciles a mutation with a read started after it, never with a poll already in flight', async () => {
    let releasePoll!: (value: unknown) => void
    const invoke = vi.fn()
      .mockResolvedValueOnce(envelope('overview', overview))
      .mockImplementationOnce(() => new Promise(resolve => { releasePoll = resolve }))
      .mockResolvedValueOnce(envelope('watch', { ...watch, user: 'bob' }))
      .mockResolvedValueOnce(envelope('overview', { ...overview, watches: [watch, { ...watch, user: 'bob' }] }))
    const ui = make(invoke)
    await ui.refresh()
    const poll = ui.refresh()
    const added = ui.add('bob', 300)
    await vi.advanceTimersByTimeAsync(0)
    releasePoll(envelope('overview', overview)); await poll
    expect(await added).toBe(true)
    expect(ui.state.overview?.watches.map(item => item.user)).toEqual(['alice', 'bob'])
    expect(invoke.mock.calls.map(call => call[0])).toEqual(['read_overview', 'read_overview', 'add_watch', 'read_overview'])
  })
  it('an uncertain outcome survives reconciliation and polling until the user refreshes', async () => {
    const invoke = vi.fn().mockResolvedValueOnce(envelope('overview', overview)).mockRejectedValueOnce('operation_timeout').mockResolvedValue(envelope('overview', overview))
    const ui = make(invoke)
    ui.start(); await vi.advanceTimersByTimeAsync(0)
    expect(await ui.pause(watch)).toBe(false)
    expect(ui.state.outcomeUnknown).toBe(true)
    await vi.advanceTimersByTimeAsync(5000)
    expect(ui.state.outcomeUnknown).toBe(true)
    await ui.refresh()
    expect(ui.state.outcomeUnknown).toBe(false)
    ui.dispose()
  })
  it('reconcile re-reads the overview without acknowledging an uncertain outcome', async () => {
    const invoke = vi.fn().mockResolvedValueOnce(envelope('overview', overview)).mockRejectedValueOnce('outcome_unknown').mockResolvedValue(envelope('overview', overview))
    const ui = make(invoke)
    await ui.refresh()
    expect(await ui.pause(watch)).toBe(false)
    expect(ui.state.outcomeUnknown).toBe(true)
    expect(await ui.reconcile()).toBe(true)
    expect(ui.state.outcomeUnknown).toBe(true) // only the user's refresh acknowledges it
    expect(invoke.mock.calls.map(call => call[0])).toEqual(['read_overview', 'pause_watch', 'read_overview', 'read_overview'])
    await ui.refresh()
    expect(ui.state.outcomeUnknown).toBe(false)
  })
  it('follows the overview cursor so registrations beyond the first page stay visible', async () => {
    const many = Array.from({ length: 50 }, (_, i) => ({ ...watch, user: `user${String(i).padStart(2, '0')}`, status: 'paused' as const }))
    const invoke = vi.fn()
      .mockResolvedValueOnce(envelope('overview', { ...overview, watches: many, next_cursor: 'w1.dXNlcjQ5' }))
      .mockResolvedValueOnce(envelope('watch_page', { items: [{ ...watch, user: 'zed' }], next_cursor: null }))
    const ui = make(invoke)
    ui.select('zed')
    expect(await ui.refresh()).toBe(true)
    expect(ui.state.overview?.watches).toHaveLength(51); expect(ui.state.overview?.next_cursor).toBeNull(); expect(ui.selected.value?.user).toBe('zed')
    expect(invoke.mock.calls[1]).toEqual(['list_watches', { page: { cursor: 'w1.dXNlcjQ5' } }])
  })
  it('removal clears the selection and refreshes once', async () => {
    const invoke = vi.fn().mockResolvedValueOnce(envelope('overview', overview)).mockResolvedValueOnce(envelope('removed', { removed_user: 'alice' })).mockResolvedValueOnce(envelope('overview', { ...overview, watches: [] }))
    const ui = make(invoke)
    await ui.refresh(); ui.select('alice'); expect(ui.selected.value?.user).toBe('alice')
    expect(await ui.remove(watch)).toBe(true)
    expect(ui.state.selectedUser).toBeNull(); expect(ui.state.overview?.watches).toHaveLength(0)
    expect(invoke.mock.calls[1]).toEqual(['remove_watch', { watch: { user: 'alice', revision: 'a'.repeat(64) } }])
  })
})
